### creating an event
POST http://localhost:5400/api/events
Content-Type: application/json

{
    "EventName": "paboyas",
    "Description": "the pabos",
    "EventDate": "03-04-2024",
    "Location": "Nairobi",
    "EventPosterURL": "click wherever"

}



###
# getting a single event
GET http://localhost:5400/api/events/128f7cff-7d95-4966-a5b6-87150338712b
Content-Type: application/json


###
# get all events

GET http://localhost:5400/api/events/allevents



### updating an event
PUT http://localhost:5400/api/events/update/3
Content-Type: application/json

{
    "EventName": "New Year Party",
    "Description": "Lets welcome the New year",
    "EventDate": "01-01-2025",
    "Location": "Everywhere",
    "EventPosterURL": "https://images.pexels.com/photos/625644/pexels-photo-625644.jpeg?auto=compress&cs=tinysrgb&w=400"
}



###
# delete an event
DELETE http://localhost:5400/api/events/delete/3