### creating an friendship
POST http://localhost:5400/api/friendship
Content-Type: application/json

{
    "User1ID": "23a5e597-7fed-4eb7-929f-201fb1465a16",
    "User2ID": "c51ed60b-4f2e-4596-b949-1427e59f6625",
    "FriendshipDate": "02-27-2024"
}



###
# getting a single friendship
GET http://localhost:5400/api/friendship/0518b1f5-03c9-49f9-8cfe-824978c0c9da
Content-Type: application/json


### getting a user's friends
GET http://localhost:5400/api/friendship/friends/23a5e597-7fed-4eb7-929f-201fb1465a16
Content-Type: application/json

###
GET http://localhost:5400/api/friendships/friends/23a5e597-7fed-4eb7-929f-201fb1465a16
Content-Type: application/json

###
# get all friendship

GET http://localhost:5400/api/friendship/allfriends



### updating an friendship
PUT http://localhost:5400/api/friendship/update/0518b1f5-03c9-49f9-8cfe-824978c0c9da
Content-Type: application/json

{
    "FriendshipDate": ""
}



###
# delete an event
DELETE http://localhost:5400/api/friendship/delete/0518b1f5-03c9-49f9-8cfe-824978c0c9da