###adding posts
POST http://localhost:5400/api/posts
Content-Type: application/json





###
# getting a single post
GET http://localhost:5400/api/posts/70d1f75c-14e0-4f0e-aa84-f4bf1b6c158a
Content-Type: application/json

### Get posts by a User
GET http://localhost:5400/api/posts/user/6bddb1bd-2dce-4a09-bb0c-5ad71ceb9012
Content-Type: application/json

###
# get all posts

GET http://localhost:5400/api/posts/all/



### updating a post
PUT http://localhost:5400/api/posts/update/70d1f75c-14e0-4f0e-aa84-f4bf1b6c158a
Content-Type: application/json

{
    "Content": "I drink and I know things",
    "PostDate" : "02-27-2024"
}



###
# delete a post
DELETE http://localhost:5400/api/posts/delete/9311a22a-0684-4ac0-a904-57f5acf8e304